apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp-sa
      containers:
        - name: webapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: webapp-config
            - secretRef:
                name: webapp-secret
          volumeMounts:
            - name: webapp-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: webapp-storage
          persistentVolumeClaim:
            claimName: webapp-pvc
