{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webapp-route
spec:
  to:
    kind: Service
    name: webapp-service
  port:
    targetPort: 5000
{{- end }}
